
/* Program generated by Cbasic 6.3.0 13633 */
#define XSCT_CBASIC

#define SCT_VERSION_6_3
#define XENABLE_VERSION_CHECK

#include "scttypes.h"
#ifdef XINCLUDE_HS_FILE
#include "PQR_sistema.hs"
#endif
XSYSTEMVARS
#ifdef XCTRACE
static char  xFileName[] = "/home/sdl/PQR/PQR_sistema.c";
#endif

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* SYSTEM PQR_sistema
* #SDTREF(SDL,/home/sdl/PQR/PQR_sistema.ssy,4,1,8)
******/
extern XCONST struct xSystemIdStruct ySysR_z_PQR_sistema;

/*****
* BLOCK PQR_bloque
* <<SYSTEM PQR_sistema>>
* #SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk,4,1,7)
******/
extern XCONST struct xBlockIdStruct yBloR_z0_PQR_bloque;

/*****
* PROCESS P
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/P.spr,4,1,9)
******/
extern XCONST XSIGTYPE yPrsS_z00_P[];
extern XCONST xStateIdNode yPrsT_z00_P[];
extern XCONST struct xPrsIdStruct yPrsR_z00_P;
#define yPrsN_z00_P  (&yPrsR_z00_P)
#ifdef XCOVERAGE
extern long int yPrsC_z00_P[];
#endif
YPAD_PROTOTYPE(yPAD_z00_P)
extern XCONST struct xSignalIdStruct ySigR_z00_P;
#define ySigN_z00_P  (&ySigR_z00_P)
typedef struct {
    SIGNAL_VARS
    STARTUP_VARS
} yPDef_z00_P;
typedef yPDef_z00_P  *yPDP_z00_P;
XPROCESSDEF_H(P,"P",z00_P,yPAD_z00_P,yVDef_z00_P)
#ifndef XOPTCHAN
extern XCONST xIdNode yPrsO_z00_P[];
#endif
#ifdef XBREAKBEFORE
#define ySym_z00_P  14
extern char * yRef_z00_P (int, xSymbolType *);
#endif
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),146(130,25),3,1) */
    SDL_Boolean z006_resP;
                /* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),146(130,25),1,7) */
    DEF_TIMER_VAR(yTim_T)
} yVDef_z00_P;
typedef yVDef_z00_P  *yVDP_z00_P;
extern void yFree_z00_P (void *);

/*****
* STATE esp_P
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS P>>
* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),122(60,115),1,1)
******/
#define z004_esp_P  1
extern XCONST struct xStateIdStruct yStaR_z004_esp_P;
#define yStaN_z004_esp_P  (&yStaR_z004_esp_P)

/*****
* TIMER T
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS P>>
* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),146(130,25),1,7)
******/
extern XCONST struct xSignalIdStruct ySigR_z005_T;
#define ySigN_z005_T  (&ySigR_z005_T)

/*****
* DCL resP
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS P>>
* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),146(130,25),3,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z006_resP;
#endif

/*****
* PROCESS R
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/R.spr,4,1,9)
******/
extern XCONST XSIGTYPE yPrsS_z01_R[];
extern XCONST xStateIdNode yPrsT_z01_R[];
extern XCONST struct xPrsIdStruct yPrsR_z01_R;
#define yPrsN_z01_R  (&yPrsR_z01_R)
#ifdef XCOVERAGE
extern long int yPrsC_z01_R[];
#endif
YPAD_PROTOTYPE(yPAD_z01_R)
extern XCONST struct xSignalIdStruct ySigR_z01_R;
#define ySigN_z01_R  (&ySigR_z01_R)
typedef struct {
    SIGNAL_VARS
    STARTUP_VARS
} yPDef_z01_R;
typedef yPDef_z01_R  *yPDP_z01_R;
XPROCESSDEF_H(R,"R",z01_R,yPAD_z01_R,yVDef_z01_R)
#ifndef XOPTCHAN
extern XCONST xIdNode yPrsO_z01_R[];
#endif
#ifdef XBREAKBEFORE
#define ySym_z01_R  19
extern char * yRef_z01_R (int, xSymbolType *);
#endif
typedef struct {
    PROCESS_VARS
} yVDef_z01_R;
typedef yVDef_z01_R  *yVDP_z01_R;
extern void yFree_z01_R (void *);

/*****
* STATE ListoR
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS R>>
* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),119(55,35),1,1)
******/
#define z013_ListoR  1
extern XCONST struct xStateIdStruct yStaR_z013_ListoR;
#define yStaN_z013_ListoR  (&yStaR_z013_ListoR)

/*****
* STATE espConfQ
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS R>>
* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),134(10,75),1,1)
******/
#define z014_espConfQ  2
extern XCONST struct xStateIdStruct yStaR_z014_espConfQ;
#define yStaN_z014_espConfQ  (&yStaR_z014_espConfQ)

/*****
* STATE espConP
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS R>>
* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),170(65,75),1,1)
******/
#define z015_espConP  3
extern XCONST struct xStateIdStruct yStaR_z015_espConP;
#define yStaN_z015_espConP  (&yStaR_z015_espConP)

/*****
* STATE espFallida
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS R>>
* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),257(140,75),1,1)
******/
#define z016_espFallida  4
extern XCONST struct xStateIdStruct yStaR_z016_espFallida;
#define yStaN_z016_espFallida  (&yStaR_z016_espFallida)

/*****
* PROCESS Q
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/Q.spr,4,1,9)
******/
extern XCONST XSIGTYPE yPrsS_z02_Q[];
extern XCONST xStateIdNode yPrsT_z02_Q[];
extern XCONST struct xPrsIdStruct yPrsR_z02_Q;
#define yPrsN_z02_Q  (&yPrsR_z02_Q)
#ifdef XCOVERAGE
extern long int yPrsC_z02_Q[];
#endif
YPAD_PROTOTYPE(yPAD_z02_Q)
extern XCONST struct xSignalIdStruct ySigR_z02_Q;
#define ySigN_z02_Q  (&ySigR_z02_Q)
typedef struct {
    SIGNAL_VARS
    STARTUP_VARS
} yPDef_z02_Q;
typedef yPDef_z02_Q  *yPDP_z02_Q;
XPROCESSDEF_H(Q,"Q",z02_Q,yPAD_z02_Q,yVDef_z02_Q)
#ifndef XOPTCHAN
extern XCONST xIdNode yPrsO_z02_Q[];
#endif
#ifdef XBREAKBEFORE
#define ySym_z02_Q  14
extern char * yRef_z02_Q (int, xSymbolType *);
#endif
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),191(130,10),3,1) */
    SDL_Boolean z026_resQ;
                /* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),191(130,10),1,7) */
    DEF_TIMER_VAR(yTim_F)
} yVDef_z02_Q;
typedef yVDef_z02_Q  *yVDP_z02_Q;
extern void yFree_z02_Q (void *);

/*****
* STATE esp_Q
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS Q>>
* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),134(85,105),1,1)
******/
#define z024_esp_Q  1
extern XCONST struct xStateIdStruct yStaR_z024_esp_Q;
#define yStaN_z024_esp_Q  (&yStaR_z024_esp_Q)

/*****
* TIMER F
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS Q>>
* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),191(130,10),1,7)
******/
extern XCONST struct xSignalIdStruct ySigR_z025_F;
#define ySigN_z025_F  (&ySigR_z025_F)

/*****
* DCL resQ
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS Q>>
* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),191(130,10),3,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z026_resQ;
#endif

/*****
* SIGNAL confP
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),143(110,25),2,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z03_confP;
#define ySigN_z03_confP  (&ySigR_z03_confP)

/*****
* SIGNAL abortP
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),143(110,25),3,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z04_abortP;
#define ySigN_z04_abortP  (&ySigR_z04_abortP)

/*****
* SIGNAL confQ
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),143(110,25),4,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z05_confQ;
#define ySigN_z05_confQ  (&ySigR_z05_confQ)

/*****
* SIGNAL abortQ
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),143(110,25),5,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z06_abortQ;
#define ySigN_z06_abortQ  (&ySigR_z06_abortQ)

/*****
* SIGNAL confR
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),143(110,25),6,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z07_confR;
#define ySigN_z07_confR  (&ySigR_z07_confR)

/*****
* SIGNAL abortR
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),143(110,25),7,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z08_abortR;
#define ySigN_z08_abortR  (&ySigR_z08_abortR)

/*****
* SIGNALROUTE R1
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),125(80,85),1,1)
******/
#ifndef XOPTCHAN
extern XCONST xIdNode yChaO_z09_R1[];
extern XCONST xIdNode yChaOR_z09_R1[];
extern XCONST struct xChannelIdStruct yChaR_z09_R1;
extern XCONST struct xChannelIdStruct yChaRR_z09_R1;
#define yChaN_z09_R1  (&yChaR_z09_R1)
#endif

/*****
* SIGNALROUTE R2
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),134(80,107),1,1)
******/
#ifndef XOPTCHAN
extern XCONST xIdNode yChaO_z0A_R2[];
extern XCONST xIdNode yChaOR_z0A_R2[];
extern XCONST struct xChannelIdStruct yChaR_z0A_R2;
extern XCONST struct xChannelIdStruct yChaRR_z0A_R2;
#define yChaN_z0A_R2  (&yChaR_z0A_R2)
#endif

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/

/*************************************************************************
**                  #CODE directives, #BODY sections                    **
*************************************************************************/

/*************************************************************************
**                  SECTION Variables and Functions                     **
*************************************************************************/

/*****
* SYSTEM PQR_sistema
* #SDTREF(SDL,/home/sdl/PQR/PQR_sistema.ssy,4,1,8)
******/
XCONST struct xSystemIdStruct ySysR_z_PQR_sistema = {xSystemEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&xSymbolTableIdRec, "PQR_sistema" XCOMMON_EXTRAS,
  (xIdNode *)0, (xPrdIdNode *)0, (xSystemIdNode)0 xTrace(-1) xGRTrace(-1)
  xMSCETrace(-1) XSYS_EXTRAS};

/*****
* ENV
******/
#ifndef XMULTIPLESYSTEMS
#ifndef XOPTCHAN
xIdNode yEnvO_env[] = {(xIdNode)0  XTRACHANNELLIST};
#endif
#endif

/*****
* BLOCK PQR_bloque
* <<SYSTEM PQR_sistema>>
* #SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk,4,1,7)
******/
XCONST struct xBlockIdStruct yBloR_z0_PQR_bloque = {xBlockEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_PQR_sistema, "PQR_bloque" XCOMMON_EXTRAS,
  (xBlockIdNode)0, (xIdNode *)0, (xPrdIdNode *)0, (xViewListRec *)0,
  (xViewIndexRec *)0, 1 xTrace(-1) xGRTrace(-1) xMSCETrace(-1) xMSCETrace(0)
  XBLO_EXTRAS};

/*****
* PROCESS P
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/P.spr,4,1,9)
******/
#ifdef XCOVERAGE
long int yPrsC_z00_P[ySym_z00_P+1];
#endif
XCONST XSIGTYPE yPrsS_z00_P[] = {SIGNAL_NAME(confR, &ySigR_z07_confR),
  SIGNAL_NAME(abortR, &ySigR_z08_abortR), SIGNAL_NAME(T, &ySigR_z005_T),
  (XSIGTYPE)0};
XCONST xStateIdNode yPrsT_z00_P[] = {&xStartStateIdRec, &yStaR_z004_esp_P};
static XPRSNODE yPrsA_z00_P = (XPRSNODE)0;
static XPRSNODE yPrsB_z00_P = (XPRSNODE)0;
XCONST struct xPrsIdStruct yPrsR_z00_P = {xProcessEC , (xIdNode)0, (xIdNode)0,
  (xIdNode)&yBloR_z0_PQR_bloque, "P" XCOMMON_EXTRAS, yPrsT_z00_P,
  yPrsS_z00_P xService(0) xOptChan(yPrsO_z00_P), -1 xNrInst(1) xNrInst(1),
  &yPrsB_z00_P, (xptrint)sizeof(yVDef_z00_P) xPrsPrioPar(xDefaultPrioProcess),
  &yPrsA_z00_P xTrace(-1) xGRTrace(-1) xBreakB(yRef_z00_P) xBreakB(ySym_z00_P)
  xBreakB(3) xMSCETrace(-1) xCoverage(yPrsC_z00_P) xCoverage(0) xCoverage(0),
  yPAD_z00_P, yFree_z00_P, (xPrsIdNode)0, (xPrdIdNode *)0, (xBlockIdNode)0
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/P.spr,4,1,9)") xThreadName(0)
  xThreadName(0) XPRS_EXTRAS(z00_P)};
static xSignalNode ySigA_z00_P = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z00_P = {xStartUpSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_PQR_bloque xIdNames("-") XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z00_P), &ySigA_z00_P, 0 xFreS(0) SIGCODE(STARTUPSIGNAL)
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/P.spr,4,1,9)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
XPROCESSDEF_C(P,"P",z00_P,yPAD_z00_P,yVDef_z00_P)
#ifndef XOPTCHAN
XCONST xIdNode yPrsO_z00_P[] = {(xIdNode)&yChaR_z09_R1, (xIdNode)0};
#endif
void yFree_z00_P(void *yVarP)
{
}

/*+++++
* GR ref function for process P
* #SDTREF(SDL,/home/sdl/PQR/P.spr,4,1,10)
++++++*/
#ifdef XBREAKBEFORE
char * yRef_z00_P (int SymbolNo, xSymbolType *SymbolType)
{
  switch (SymbolNo) {
    case 0: *SymbolType = xsStart;
      return "#SDTREF(SDL,/home/sdl/PQR/P.spr(1),119(60,30),1,1)";
    case 1: *SymbolType = xsInput;
      return "#SDTREF(SDL,/home/sdl/PQR/P.spr(1),131(35,135),1,1)";
    case 2: *SymbolType = xsInput;
      return "#SDTREF(SDL,/home/sdl/PQR/P.spr(1),134(85,135),1,1)";
    case 3: *SymbolType = xsInput;
      return "#SDTREF(SDL,/home/sdl/PQR/P.spr(1),227(125,135),1,1)";
    case 4: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,/home/sdl/PQR/P.spr(1),125(60,50),1,1)";
    case 5: *SymbolType = xsDecision;
      return "#SDTREF(SDL,/home/sdl/PQR/P.spr(1),149(60,70),1,1)";
    case 6: *SymbolType = xsOutput;
      return "#SDTREF(SDL,/home/sdl/PQR/P.spr(1),128(40,85),1,1)";
    case 7: *SymbolType = xsOutput;
      return "#SDTREF(SDL,/home/sdl/PQR/P.spr(1),152(80,85),1,1)";
    case 8: *SymbolType = xsSet;
      return "#SDTREF(SDL,/home/sdl/PQR/P.spr(1),215(60,100),1,1)";
    case 9: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,/home/sdl/PQR/P.spr(1),122(60,115),1,1)";
    case 10: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,/home/sdl/PQR/P.spr(1),167(60,155),1,1)";
    case 11: *SymbolType = xsDecision;
      return "#SDTREF(SDL,/home/sdl/PQR/P.spr(1),173(60,170),1,1)";
    case 12: *SymbolType = xsOutput;
      return "#SDTREF(SDL,/home/sdl/PQR/P.spr(1),176(40,185),1,1)";
    case 13: *SymbolType = xsOutput;
      return "#SDTREF(SDL,/home/sdl/PQR/P.spr(1),170(80,185),1,1)";
    case 14: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,/home/sdl/PQR/P.spr(1),179(60,205),1,1)";
    default : *SymbolType = xsNoSuchSymbolType; return "";
  }
}
#endif

/*+++++
* Function for process P
* #SDTREF(SDL,/home/sdl/PQR/P.spr,4,1,10)
++++++*/
YPAD_FUNCTION(yPAD_z00_P)
{
  YPAD_YSVARP
  YPAD_YVARP(yVDef_z00_P)
  YPAD_TEMP_VARS
#ifdef XTRACE
  SDL_Boolean yDcn_SDL_Boolean;
#endif
  YPRSNAME_VAR("P")

  BEGIN_PAD(yVDef_z00_P)

  LOOP_LABEL
  switch (yVarP->RestartAddress) {

/* ----- START ----- */
/* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),119(60,30),1,1) */
  case 0:
    BEGIN_START_TRANSITION(yPDef_z00_P)
    XAT_FIRST_SYMBOL(0)
    INIT_TIMER_VAR(yVarP->yTim_T)
    XBETWEEN_SYMBOLS(4, 452)

/* ----- ASSIGNMENT resP := ... ----- */
/* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),125(60,50),1,1) */
#ifdef XCASELABELS
  case 4:
#endif
    yAssF_SDL_Boolean(yVarP->z006_resP, ANY_SDL_Boolean, XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("resP := ", &(yVarP->z006_resP),
      (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
#ifdef XMSCE
    xMSCEAssign(VarP, "resP := ", &(yVarP->z006_resP),
      (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif

  L_1:;
    XBETWEEN_SYMBOLS(5, 470)

/* ----- DECISION ----- */
/* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),149(60,70),1,1) */
#ifdef XCASELABELS
  case 5:
#endif
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean, yVarP->z006_resP, XASS_MR_ASS_FR);
    xTraceDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#ifdef XMSCE
    xMSCEDecision(VarP, &(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
    if (yDcn_SDL_Boolean) {
  #else
  if (yVarP->z006_resP) {
  #endif
    XBETWEEN_SYMBOLS(6, 487)

/* ----- OUTPUT confP ----- */
/* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),128(40,85),1,1) */
#ifdef XCASELABELS
  case 6:
#endif
    ALLOC_SIGNAL(confP, ySigN_z03_confP, TO_PROCESS(R, yPrsN_z01_R),
      XSIGNALHEADERTYPE)
    SIGNAL_ALLOC_ERROR
    SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, (xIdNode *)0, confP,
      ySigN_z03_confP, TO_PROCESS(R, yPrsN_z01_R), 0, "confP")
    SIGNAL_ALLOC_ERROR_END
  } else {
    XBETWEEN_SYMBOLS(7, 501)

/* ----- OUTPUT abortP ----- */
/* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),152(80,85),1,1) */
#ifdef XCASELABELS
  case 7:
#endif
    ALLOC_SIGNAL(abortP, ySigN_z04_abortP, TO_PROCESS(R, yPrsN_z01_R),
      XSIGNALHEADERTYPE)
    SIGNAL_ALLOC_ERROR
    SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, (xIdNode *)0, abortP,
      ySigN_z04_abortP, TO_PROCESS(R, yPrsN_z01_R), 0, "abortP")
    SIGNAL_ALLOC_ERROR_END
  }
    XBETWEEN_SYMBOLS(8, 515)

/* ----- SET T ----- */
/* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),215(60,100),1,1) */
#ifdef XCASELABELS
  case 8:
#endif
    SDL_SET_DUR(xPlus_SDL_Time(SDL_NOW, SDL_DURATION_LIT(1.0, 1, 0)),
      SDL_DURATION_LIT(1.0, 1, 0), T, ySigN_z005_T, yVarP->yTim_T, "T")
    XBETWEEN_SYMBOLS(9, 524)

/* ----- NEXTSTATE esp_P ----- */
/* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),122(60,115),1,1) */
#ifdef XCASELABELS
  case 9:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(esp_P, z004_esp_P, "esp_P")

/* ----- INPUT confR in STATE esp_P ----- */
/* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),131(35,135),1,1) */
  case 1:
    XDEBUG_LABEL(esp_P_confR)
    XAT_FIRST_SYMBOL(1)
    XOS_TRACE_INPUT("confR")

  L_grst9270_1:;
    XBETWEEN_SYMBOLS(10, 542)

/* ----- ASSIGNMENT resP := ... ----- */
/* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),167(60,155),1,1) */
#ifdef XCASELABELS
  case 10:
#endif
    yAssF_SDL_Boolean(yVarP->z006_resP, ANY_SDL_Boolean, XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("resP := ", &(yVarP->z006_resP),
      (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
#ifdef XMSCE
    xMSCEAssign(VarP, "resP := ", &(yVarP->z006_resP),
      (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
    XBETWEEN_SYMBOLS(11, 558)

/* ----- DECISION ----- */
/* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),173(60,170),1,1) */
#ifdef XCASELABELS
  case 11:
#endif
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean, yVarP->z006_resP, XASS_MR_ASS_FR);
    xTraceDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#ifdef XMSCE
    xMSCEDecision(VarP, &(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
    if (yDcn_SDL_Boolean) {
  #else
  if (yVarP->z006_resP) {
  #endif
    XBETWEEN_SYMBOLS(12, 575)

/* ----- OUTPUT confP ----- */
/* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),176(40,185),1,1) */
#ifdef XCASELABELS
  case 12:
#endif
    ALLOC_SIGNAL(confP, ySigN_z03_confP, TO_PROCESS(R, yPrsN_z01_R),
      XSIGNALHEADERTYPE)
    SIGNAL_ALLOC_ERROR
    SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, (xIdNode *)0, confP,
      ySigN_z03_confP, TO_PROCESS(R, yPrsN_z01_R), 0, "confP")
    SIGNAL_ALLOC_ERROR_END
  } else {
    XBETWEEN_SYMBOLS(13, 589)

/* ----- OUTPUT abortP ----- */
/* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),170(80,185),1,1) */
#ifdef XCASELABELS
  case 13:
#endif
    ALLOC_SIGNAL(abortP, ySigN_z04_abortP, TO_PROCESS(R, yPrsN_z01_R),
      XSIGNALHEADERTYPE)
    SIGNAL_ALLOC_ERROR
    SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, (xIdNode *)0, abortP,
      ySigN_z04_abortP, TO_PROCESS(R, yPrsN_z01_R), 0, "abortP")
    SIGNAL_ALLOC_ERROR_END
  }
    XBETWEEN_SYMBOLS(14, 603)

/* ----- NEXTSTATE esp_P ----- */
/* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),179(60,205),1,1) */
#ifdef XCASELABELS
  case 14:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(esp_P, z004_esp_P, "esp_P")

/* ----- INPUT abortR in STATE esp_P ----- */
/* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),134(85,135),1,1) */
  case 2:
    XDEBUG_LABEL(esp_P_abortR)
    XAT_FIRST_SYMBOL(2)
    XOS_TRACE_INPUT("abortR")

/* ----- JOIN grst9270_1 ----- */
/* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),167(60,155),1,1) */
    goto L_grst9270_1;

/* ----- INPUT T in STATE esp_P ----- */
/* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),227(125,135),1,1) */
  case 3:
    XDEBUG_LABEL(esp_P_T)
    XAT_FIRST_SYMBOL(3)
    XOS_TRACE_INPUT("T")
    INPUT_TIMER_VAR(yVarP->yTim_T)

/* ----- JOIN 1 ----- */
/* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),233(130,160),1,1) */
    goto L_1;
  default : return;
  }
}

/*****
* STATE esp_P
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS P>>
* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),122(60,115),1,1)
******/
static XCONST xInputAction yStaH_z004_esp_P[] = {xInput, xInput, xInput,
  xDiscard};
static XCONST XINPUTREFTYPE yStaI_z004_esp_P[] = {1, 2, 3, 0};
#ifdef XCOVERAGE
static long int yStaC_z004_esp_P[3+1];
#endif
XCONST struct xStateIdStruct yStaR_z004_esp_P = {xStateEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z00_P, "esp_P" XCOMMON_EXTRAS, z004_esp_P,
  yStaH_z004_esp_P, yStaI_z004_esp_P, 0, 0, 0 xCoverage(yStaC_z004_esp_P),
  (xStateIdNode)0
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/P.spr(1),122(60,115),1,1)") XSTA_EXTRAS};

/*****
* TIMER T
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS P>>
* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),146(130,25),1,7)
******/
XCONST struct xSignalIdStruct ySigR_z005_T = {xTimerEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z00_P, "T" XCOMMON_EXTRAS,
  (xptrint)sizeof(XTIMERHEADERTYPE), 0, 0 xFreS(0) SIGCODE(T)
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/P.spr(1),146(130,25),1,7)")
  xSigPrioPar(xDefaultPrioSignal) OFFSET_TIMER_VAR(yTim_T, yVDef_z00_P)
  XSIG_EXTRAS};

/*****
* DCL resP
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS P>>
* #SDTREF(SDL,/home/sdl/PQR/P.spr(1),146(130,25),3,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z006_resP = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z00_P, "resP" XCOMMON_EXTRAS, &xSrtR_SDL_Boolean,
  (tSDLTypeInfo *)&ySDL_SDL_Boolean, xOffsetOf(yVDef_z00_P, z006_resP),
  (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* PROCESS R
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/R.spr,4,1,9)
******/
#ifdef XCOVERAGE
long int yPrsC_z01_R[ySym_z01_R+1];
#endif
XCONST XSIGTYPE yPrsS_z01_R[] = {SIGNAL_NAME(confP, &ySigR_z03_confP),
  SIGNAL_NAME(abortP, &ySigR_z04_abortP), SIGNAL_NAME(confQ, &ySigR_z05_confQ),
  SIGNAL_NAME(abortQ, &ySigR_z06_abortQ), (XSIGTYPE)0};
XCONST xStateIdNode yPrsT_z01_R[] = {&xStartStateIdRec, &yStaR_z013_ListoR,
  &yStaR_z014_espConfQ, &yStaR_z015_espConP, &yStaR_z016_espFallida};
static XPRSNODE yPrsA_z01_R = (XPRSNODE)0;
static XPRSNODE yPrsB_z01_R = (XPRSNODE)0;
XCONST struct xPrsIdStruct yPrsR_z01_R = {xProcessEC , (xIdNode)0, (xIdNode)0,
  (xIdNode)&yBloR_z0_PQR_bloque, "R" XCOMMON_EXTRAS, yPrsT_z01_R,
  yPrsS_z01_R xService(0) xOptChan(yPrsO_z01_R), -1 xNrInst(1) xNrInst(1),
  &yPrsB_z01_R, (xptrint)sizeof(yVDef_z01_R) xPrsPrioPar(xDefaultPrioProcess),
  &yPrsA_z01_R xTrace(-1) xGRTrace(-1) xBreakB(yRef_z01_R) xBreakB(ySym_z01_R)
  xBreakB(4) xMSCETrace(-1) xCoverage(yPrsC_z01_R) xCoverage(0) xCoverage(0),
  yPAD_z01_R, yFree_z01_R, (xPrsIdNode)0, (xPrdIdNode *)0, (xBlockIdNode)0
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/R.spr,4,1,9)") xThreadName(0)
  xThreadName(0) XPRS_EXTRAS(z01_R)};
static xSignalNode ySigA_z01_R = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z01_R = {xStartUpSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_PQR_bloque xIdNames("-") XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z01_R), &ySigA_z01_R, 0 xFreS(0) SIGCODE(STARTUPSIGNAL)
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/R.spr,4,1,9)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
XPROCESSDEF_C(R,"R",z01_R,yPAD_z01_R,yVDef_z01_R)
#ifndef XOPTCHAN
XCONST xIdNode yPrsO_z01_R[] = {(xIdNode)&yChaRR_z09_R1,
  (xIdNode)&yChaRR_z0A_R2, (xIdNode)0};
#endif
void yFree_z01_R(void *yVarP)
{
}

/*+++++
* GR ref function for process R
* #SDTREF(SDL,/home/sdl/PQR/R.spr,4,1,10)
++++++*/
#ifdef XBREAKBEFORE
char * yRef_z01_R (int SymbolNo, xSymbolType *SymbolType)
{
  switch (SymbolNo) {
    case 0: *SymbolType = xsStart;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),116(55,15),1,1)";
    case 1: *SymbolType = xsInput;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),122(10,55),1,1)";
    case 2: *SymbolType = xsInput;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),125(65,55),1,1)";
    case 3: *SymbolType = xsInput;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),221(125,55),1,1)";
    case 4: *SymbolType = xsInput;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),227(160,55),1,1)";
    case 5: *SymbolType = xsInput;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),128(35,95),1,1)";
    case 6: *SymbolType = xsInput;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),137(10,100),1,1)";
    case 7: *SymbolType = xsInput;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),131(90,95),1,1)";
    case 8: *SymbolType = xsInput;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),173(65,100),1,1)";
    case 9: *SymbolType = xsInput;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),317(140,90),1,1)";
    case 10: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),119(55,35),1,1)";
    case 11: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),134(10,75),1,1)";
    case 12: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),170(65,75),1,1)";
    case 13: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),257(140,75),1,1)";
    case 14: *SymbolType = xsOutput;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),194(125,130),1,1)";
    case 15: *SymbolType = xsOutput;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),197(125,145),1,1)";
    case 16: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),200(125,160),1,1)";
    case 17: *SymbolType = xsOutput;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),140(10,120),1,1)";
    case 18: *SymbolType = xsOutput;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),143(10,140),1,1)";
    case 19: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,/home/sdl/PQR/R.spr(1),146(10,160),1,1)";
    default : *SymbolType = xsNoSuchSymbolType; return "";
  }
}
#endif

/*+++++
* Function for process R
* #SDTREF(SDL,/home/sdl/PQR/R.spr,4,1,10)
++++++*/
YPAD_FUNCTION(yPAD_z01_R)
{
  YPAD_YSVARP
  YPAD_YVARP(yVDef_z01_R)
  YPAD_TEMP_VARS
#ifndef XOPTCHAN
  xIdNode  yViaList[2];
#endif
  YPRSNAME_VAR("R")

  BEGIN_PAD(yVDef_z01_R)

  LOOP_LABEL
  switch (yVarP->RestartAddress) {

/* ----- START ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),116(55,15),1,1) */
  case 0:
    BEGIN_START_TRANSITION(yPDef_z01_R)
    XAT_FIRST_SYMBOL(0)
    XBETWEEN_SYMBOLS(10, 796)

/* ----- NEXTSTATE ListoR ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),119(55,35),1,1) */
#ifdef XCASELABELS
  case 10:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(ListoR, z013_ListoR, "ListoR")

/* ----- INPUT confP in STATE ListoR ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),122(10,55),1,1) */
  case 1:
    XDEBUG_LABEL(ListoR_confP)
    XAT_FIRST_SYMBOL(1)
    XOS_TRACE_INPUT("confP")
    XBETWEEN_SYMBOLS(11, 812)

/* ----- NEXTSTATE espConfQ ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),134(10,75),1,1) */
#ifdef XCASELABELS
  case 11:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(espConfQ, z014_espConfQ, "espConfQ")

/* ----- INPUT confQ in STATE ListoR ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),125(65,55),1,1) */
  case 2:
    XDEBUG_LABEL(ListoR_confQ)
    XAT_FIRST_SYMBOL(2)
    XOS_TRACE_INPUT("confQ")
    XBETWEEN_SYMBOLS(12, 828)

/* ----- NEXTSTATE espConP ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),170(65,75),1,1) */
#ifdef XCASELABELS
  case 12:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(espConP, z015_espConP, "espConP")

/* ----- INPUT abortP in STATE ListoR ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),221(125,55),1,1) */
  case 3:
    XDEBUG_LABEL(ListoR_abortP)
    XAT_FIRST_SYMBOL(3)
    XOS_TRACE_INPUT("abortP")

  L_grst9272_1:;
    XBETWEEN_SYMBOLS(13, 846)

/* ----- NEXTSTATE espFallida ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),257(140,75),1,1) */
#ifdef XCASELABELS
  case 13:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(espFallida, z016_espFallida, "espFallida")

/* ----- INPUT abortQ in STATE ListoR ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),227(160,55),1,1) */
  case 4:
    XDEBUG_LABEL(ListoR_abortQ)
    XAT_FIRST_SYMBOL(4)
    XOS_TRACE_INPUT("abortQ")

/* ----- JOIN grst9272_1 ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),257(140,75),1,1) */
    goto L_grst9272_1;

/* ----- INPUT abortQ in STATE espConfQ ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),128(35,95),1,1) */
  case 5:
    XDEBUG_LABEL(espConfQ_abortQ)
    XAT_FIRST_SYMBOL(5)
    XOS_TRACE_INPUT("abortQ")

  L_grst9272_2:;
    XBETWEEN_SYMBOLS(14, 875)

/* ----- OUTPUT abortR ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),194(125,130),1,1) */
#ifdef XCASELABELS
  case 14:
#endif
#ifndef XOPTCHAN
    yViaList[0] = (xIdNode)&yChaRR_z09_R1;
    yViaList[1] = (xIdNode)0;
#endif
    ALLOC_SIGNAL(abortR, ySigN_z08_abortR, TO_PROCESS(P, yPrsN_z00_P),
      XSIGNALHEADERTYPE)
    SIGNAL_ALLOC_ERROR
    SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, yViaList, abortR,
      ySigN_z08_abortR, TO_PROCESS(P, yPrsN_z00_P), 0, "abortR")
    SIGNAL_ALLOC_ERROR_END
    XBETWEEN_SYMBOLS(15, 892)

/* ----- OUTPUT abortR ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),197(125,145),1,1) */
#ifdef XCASELABELS
  case 15:
#endif
#ifndef XOPTCHAN
    yViaList[0] = (xIdNode)&yChaRR_z0A_R2;
    yViaList[1] = (xIdNode)0;
#endif
    ALLOC_SIGNAL(abortR, ySigN_z08_abortR, TO_PROCESS(Q, yPrsN_z02_Q),
      XSIGNALHEADERTYPE)
    SIGNAL_ALLOC_ERROR
    SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, yViaList, abortR,
      ySigN_z08_abortR, TO_PROCESS(Q, yPrsN_z02_Q), 0, "abortR")
    SIGNAL_ALLOC_ERROR_END
    XBETWEEN_SYMBOLS(16, 909)

/* ----- NEXTSTATE ListoR ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),200(125,160),1,1) */
#ifdef XCASELABELS
  case 16:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(ListoR, z013_ListoR, "ListoR")

/* ----- INPUT confQ in STATE espConfQ ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),137(10,100),1,1) */
  case 6:
    XDEBUG_LABEL(espConfQ_confQ)
    XAT_FIRST_SYMBOL(6)
    XOS_TRACE_INPUT("confQ")

  L_grst9272_3:;
    XBETWEEN_SYMBOLS(17, 927)

/* ----- OUTPUT confR ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),140(10,120),1,1) */
#ifdef XCASELABELS
  case 17:
#endif
#ifndef XOPTCHAN
    yViaList[0] = (xIdNode)&yChaRR_z09_R1;
    yViaList[1] = (xIdNode)0;
#endif
    ALLOC_SIGNAL(confR, ySigN_z07_confR, TO_PROCESS(P, yPrsN_z00_P),
      XSIGNALHEADERTYPE)
    SIGNAL_ALLOC_ERROR
    SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, yViaList, confR,
      ySigN_z07_confR, TO_PROCESS(P, yPrsN_z00_P), 0, "confR")
    SIGNAL_ALLOC_ERROR_END
    XBETWEEN_SYMBOLS(18, 944)

/* ----- OUTPUT confR ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),143(10,140),1,1) */
#ifdef XCASELABELS
  case 18:
#endif
#ifndef XOPTCHAN
    yViaList[0] = (xIdNode)&yChaRR_z0A_R2;
    yViaList[1] = (xIdNode)0;
#endif
    ALLOC_SIGNAL(confR, ySigN_z07_confR, TO_PROCESS(Q, yPrsN_z02_Q),
      XSIGNALHEADERTYPE)
    SIGNAL_ALLOC_ERROR
    SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, yViaList, confR,
      ySigN_z07_confR, TO_PROCESS(Q, yPrsN_z02_Q), 0, "confR")
    SIGNAL_ALLOC_ERROR_END
    XBETWEEN_SYMBOLS(19, 961)

/* ----- NEXTSTATE ListoR ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),146(10,160),1,1) */
#ifdef XCASELABELS
  case 19:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(ListoR, z013_ListoR, "ListoR")

/* ----- INPUT abortP in STATE espConP ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),131(90,95),1,1) */
  case 7:
    XDEBUG_LABEL(espConP_abortP)
    XAT_FIRST_SYMBOL(7)
    XOS_TRACE_INPUT("abortP")

/* ----- JOIN grst9272_2 ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),194(125,130),1,1) */
    goto L_grst9272_2;

/* ----- INPUT confP in STATE espConP ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),173(65,100),1,1) */
  case 8:
    XDEBUG_LABEL(espConP_confP)
    XAT_FIRST_SYMBOL(8)
    XOS_TRACE_INPUT("confP")

/* ----- JOIN grst9272_3 ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),140(10,120),1,1) */
    goto L_grst9272_3;

/* ----- INPUT * in STATE espFallida ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),317(140,90),1,1) */
  case 9:
    XDEBUG_LABEL(espFallida_ASTERISK)
    XAT_FIRST_SYMBOL(9)
    XOS_TRACE_INPUT("*")
#ifdef XRELEASE_SIGNAL_PARS
    XRELEASE_SIGNAL_PARS
#endif

/* ----- JOIN grst9272_2 ----- */
/* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),194(125,130),1,1) */
    goto L_grst9272_2;
  default : return;
  }
}

/*****
* STATE ListoR
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS R>>
* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),119(55,35),1,1)
******/
static XCONST xInputAction yStaH_z013_ListoR[] = {xInput, xInput, xInput,
  xInput, xDiscard};
static XCONST XINPUTREFTYPE yStaI_z013_ListoR[] = {1, 3, 2, 4, 0};
#ifdef XCOVERAGE
static long int yStaC_z013_ListoR[4+1];
#endif
XCONST struct xStateIdStruct yStaR_z013_ListoR = {xStateEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z01_R, "ListoR" XCOMMON_EXTRAS, z013_ListoR,
  yStaH_z013_ListoR, yStaI_z013_ListoR, 0, 0, 0 xCoverage(yStaC_z013_ListoR),
  (xStateIdNode)0 xBreakB("#SDTREF(SDL,/home/sdl/PQR/R.spr(1),119(55,35),1,1)")
  XSTA_EXTRAS};

/*****
* STATE espConfQ
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS R>>
* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),134(10,75),1,1)
******/
static XCONST xInputAction yStaH_z014_espConfQ[] = {xDiscard, xDiscard, xInput,
  xInput, xDiscard};
static XCONST XINPUTREFTYPE yStaI_z014_espConfQ[] = {0, 0, 6, 5, 0};
#ifdef XCOVERAGE
static long int yStaC_z014_espConfQ[4+1];
#endif
XCONST struct xStateIdStruct yStaR_z014_espConfQ = {xStateEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z01_R, "espConfQ" XCOMMON_EXTRAS, z014_espConfQ,
  yStaH_z014_espConfQ, yStaI_z014_espConfQ, 0, 0, 0
  xCoverage(yStaC_z014_espConfQ), (xStateIdNode)0
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/R.spr(1),134(10,75),1,1)") XSTA_EXTRAS};

/*****
* STATE espConP
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS R>>
* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),170(65,75),1,1)
******/
static XCONST xInputAction yStaH_z015_espConP[] = {xInput, xInput, xDiscard,
  xDiscard, xDiscard};
static XCONST XINPUTREFTYPE yStaI_z015_espConP[] = {8, 7, 0, 0, 0};
#ifdef XCOVERAGE
static long int yStaC_z015_espConP[4+1];
#endif
XCONST struct xStateIdStruct yStaR_z015_espConP = {xStateEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z01_R, "espConP" XCOMMON_EXTRAS, z015_espConP,
  yStaH_z015_espConP, yStaI_z015_espConP, 0, 0, 0
  xCoverage(yStaC_z015_espConP), (xStateIdNode)0
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/R.spr(1),170(65,75),1,1)") XSTA_EXTRAS};

/*****
* STATE espFallida
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS R>>
* #SDTREF(SDL,/home/sdl/PQR/R.spr(1),257(140,75),1,1)
******/
static XCONST xInputAction yStaH_z016_espFallida[] = {xInput, xInput, xInput,
  xInput, xInput};
static XCONST XINPUTREFTYPE yStaI_z016_espFallida[] = {9, 9, 9, 9, 9};
#ifdef XCOVERAGE
static long int yStaC_z016_espFallida[4+1];
#endif
XCONST struct xStateIdStruct yStaR_z016_espFallida = {xStateEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z01_R, "espFallida" XCOMMON_EXTRAS,
  z016_espFallida, yStaH_z016_espFallida, yStaI_z016_espFallida, 0, 0, 0
  xCoverage(yStaC_z016_espFallida), (xStateIdNode)0
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/R.spr(1),257(140,75),1,1)") XSTA_EXTRAS};

/*****
* PROCESS Q
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/Q.spr,4,1,9)
******/
#ifdef XCOVERAGE
long int yPrsC_z02_Q[ySym_z02_Q+1];
#endif
XCONST XSIGTYPE yPrsS_z02_Q[] = {SIGNAL_NAME(confR, &ySigR_z07_confR),
  SIGNAL_NAME(abortR, &ySigR_z08_abortR), SIGNAL_NAME(F, &ySigR_z025_F),
  (XSIGTYPE)0};
XCONST xStateIdNode yPrsT_z02_Q[] = {&xStartStateIdRec, &yStaR_z024_esp_Q};
static XPRSNODE yPrsA_z02_Q = (XPRSNODE)0;
static XPRSNODE yPrsB_z02_Q = (XPRSNODE)0;
XCONST struct xPrsIdStruct yPrsR_z02_Q = {xProcessEC , (xIdNode)0, (xIdNode)0,
  (xIdNode)&yBloR_z0_PQR_bloque, "Q" XCOMMON_EXTRAS, yPrsT_z02_Q,
  yPrsS_z02_Q xService(0) xOptChan(yPrsO_z02_Q), -1 xNrInst(1) xNrInst(1),
  &yPrsB_z02_Q, (xptrint)sizeof(yVDef_z02_Q) xPrsPrioPar(xDefaultPrioProcess),
  &yPrsA_z02_Q xTrace(-1) xGRTrace(-1) xBreakB(yRef_z02_Q) xBreakB(ySym_z02_Q)
  xBreakB(3) xMSCETrace(-1) xCoverage(yPrsC_z02_Q) xCoverage(0) xCoverage(0),
  yPAD_z02_Q, yFree_z02_Q, (xPrsIdNode)0, (xPrdIdNode *)0, (xBlockIdNode)0
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/Q.spr,4,1,9)") xThreadName(0)
  xThreadName(0) XPRS_EXTRAS(z02_Q)};
static xSignalNode ySigA_z02_Q = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z02_Q = {xStartUpSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_PQR_bloque xIdNames("-") XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z02_Q), &ySigA_z02_Q, 0 xFreS(0) SIGCODE(STARTUPSIGNAL)
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/Q.spr,4,1,9)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
XPROCESSDEF_C(Q,"Q",z02_Q,yPAD_z02_Q,yVDef_z02_Q)
#ifndef XOPTCHAN
XCONST xIdNode yPrsO_z02_Q[] = {(xIdNode)&yChaR_z0A_R2, (xIdNode)0};
#endif
void yFree_z02_Q(void *yVarP)
{
}

/*+++++
* GR ref function for process Q
* #SDTREF(SDL,/home/sdl/PQR/Q.spr,4,1,10)
++++++*/
#ifdef XBREAKBEFORE
char * yRef_z02_Q (int SymbolNo, xSymbolType *SymbolType)
{
  switch (SymbolNo) {
    case 0: *SymbolType = xsStart;
      return "#SDTREF(SDL,/home/sdl/PQR/Q.spr(1),149(85,20),1,1)";
    case 1: *SymbolType = xsInput;
      return "#SDTREF(SDL,/home/sdl/PQR/Q.spr(1),131(60,120),1,1)";
    case 2: *SymbolType = xsInput;
      return "#SDTREF(SDL,/home/sdl/PQR/Q.spr(1),194(110,120),1,1)";
    case 3: *SymbolType = xsInput;
      return "#SDTREF(SDL,/home/sdl/PQR/Q.spr(1),212(145,120),1,1)";
    case 4: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,/home/sdl/PQR/Q.spr(1),146(85,40),1,1)";
    case 5: *SymbolType = xsDecision;
      return "#SDTREF(SDL,/home/sdl/PQR/Q.spr(1),143(85,60),1,1)";
    case 6: *SymbolType = xsOutput;
      return "#SDTREF(SDL,/home/sdl/PQR/Q.spr(1),140(65,75),1,1)";
    case 7: *SymbolType = xsOutput;
      return "#SDTREF(SDL,/home/sdl/PQR/Q.spr(1),137(105,75),1,1)";
    case 8: *SymbolType = xsSet;
      return "#SDTREF(SDL,/home/sdl/PQR/Q.spr(1),209(85,90),1,1)";
    case 9: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,/home/sdl/PQR/Q.spr(1),134(85,105),1,1)";
    case 10: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,/home/sdl/PQR/Q.spr(1),128(85,140),1,1)";
    case 11: *SymbolType = xsDecision;
      return "#SDTREF(SDL,/home/sdl/PQR/Q.spr(1),125(85,160),1,1)";
    case 12: *SymbolType = xsOutput;
      return "#SDTREF(SDL,/home/sdl/PQR/Q.spr(1),122(65,175),1,1)";
    case 13: *SymbolType = xsOutput;
      return "#SDTREF(SDL,/home/sdl/PQR/Q.spr(1),119(105,175),1,1)";
    case 14: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,/home/sdl/PQR/Q.spr(1),116(85,195),1,1)";
    default : *SymbolType = xsNoSuchSymbolType; return "";
  }
}
#endif

/*+++++
* Function for process Q
* #SDTREF(SDL,/home/sdl/PQR/Q.spr,4,1,10)
++++++*/
YPAD_FUNCTION(yPAD_z02_Q)
{
  YPAD_YSVARP
  YPAD_YVARP(yVDef_z02_Q)
  YPAD_TEMP_VARS
#ifdef XTRACE
  SDL_Boolean yDcn_SDL_Boolean;
#endif
  YPRSNAME_VAR("Q")

  BEGIN_PAD(yVDef_z02_Q)

  LOOP_LABEL
  switch (yVarP->RestartAddress) {

/* ----- START ----- */
/* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),149(85,20),1,1) */
  case 0:
    BEGIN_START_TRANSITION(yPDef_z02_Q)
    XAT_FIRST_SYMBOL(0)
    INIT_TIMER_VAR(yVarP->yTim_F)
    XBETWEEN_SYMBOLS(4, 1183)

/* ----- ASSIGNMENT resQ := ... ----- */
/* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),146(85,40),1,1) */
#ifdef XCASELABELS
  case 4:
#endif
    yAssF_SDL_Boolean(yVarP->z026_resQ, ANY_SDL_Boolean, XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("resQ := ", &(yVarP->z026_resQ),
      (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
#ifdef XMSCE
    xMSCEAssign(VarP, "resQ := ", &(yVarP->z026_resQ),
      (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif

  L_1:;
    XBETWEEN_SYMBOLS(5, 1201)

/* ----- DECISION ----- */
/* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),143(85,60),1,1) */
#ifdef XCASELABELS
  case 5:
#endif
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean, yVarP->z026_resQ, XASS_MR_ASS_FR);
    xTraceDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#ifdef XMSCE
    xMSCEDecision(VarP, &(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
    if (yDcn_SDL_Boolean) {
  #else
  if (yVarP->z026_resQ) {
  #endif
    XBETWEEN_SYMBOLS(6, 1218)

/* ----- OUTPUT confQ ----- */
/* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),140(65,75),1,1) */
#ifdef XCASELABELS
  case 6:
#endif
    ALLOC_SIGNAL(confQ, ySigN_z05_confQ, TO_PROCESS(R, yPrsN_z01_R),
      XSIGNALHEADERTYPE)
    SIGNAL_ALLOC_ERROR
    SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, (xIdNode *)0, confQ,
      ySigN_z05_confQ, TO_PROCESS(R, yPrsN_z01_R), 0, "confQ")
    SIGNAL_ALLOC_ERROR_END
  } else {
    XBETWEEN_SYMBOLS(7, 1232)

/* ----- OUTPUT abortQ ----- */
/* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),137(105,75),1,1) */
#ifdef XCASELABELS
  case 7:
#endif
    ALLOC_SIGNAL(abortQ, ySigN_z06_abortQ, TO_PROCESS(R, yPrsN_z01_R),
      XSIGNALHEADERTYPE)
    SIGNAL_ALLOC_ERROR
    SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, (xIdNode *)0, abortQ,
      ySigN_z06_abortQ, TO_PROCESS(R, yPrsN_z01_R), 0, "abortQ")
    SIGNAL_ALLOC_ERROR_END
  }
    XBETWEEN_SYMBOLS(8, 1246)

/* ----- SET F ----- */
/* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),209(85,90),1,1) */
#ifdef XCASELABELS
  case 8:
#endif
    SDL_SET_DUR(xPlus_SDL_Time(SDL_NOW, SDL_DURATION_LIT(1.0, 1, 0)),
      SDL_DURATION_LIT(1.0, 1, 0), F, ySigN_z025_F, yVarP->yTim_F, "F")
    XBETWEEN_SYMBOLS(9, 1255)

/* ----- NEXTSTATE esp_Q ----- */
/* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),134(85,105),1,1) */
#ifdef XCASELABELS
  case 9:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(esp_Q, z024_esp_Q, "esp_Q")

/* ----- INPUT confR in STATE esp_Q ----- */
/* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),131(60,120),1,1) */
  case 1:
    XDEBUG_LABEL(esp_Q_confR)
    XAT_FIRST_SYMBOL(1)
    XOS_TRACE_INPUT("confR")

  L_grst9271_1:;
    XBETWEEN_SYMBOLS(10, 1273)

/* ----- ASSIGNMENT resQ := ... ----- */
/* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),128(85,140),1,1) */
#ifdef XCASELABELS
  case 10:
#endif
    yAssF_SDL_Boolean(yVarP->z026_resQ, ANY_SDL_Boolean, XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("resQ := ", &(yVarP->z026_resQ),
      (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
#ifdef XMSCE
    xMSCEAssign(VarP, "resQ := ", &(yVarP->z026_resQ),
      (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
    XBETWEEN_SYMBOLS(11, 1289)

/* ----- DECISION ----- */
/* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),125(85,160),1,1) */
#ifdef XCASELABELS
  case 11:
#endif
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean, yVarP->z026_resQ, XASS_MR_ASS_FR);
    xTraceDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#ifdef XMSCE
    xMSCEDecision(VarP, &(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
    if (yDcn_SDL_Boolean) {
  #else
  if (yVarP->z026_resQ) {
  #endif
    XBETWEEN_SYMBOLS(12, 1306)

/* ----- OUTPUT confQ ----- */
/* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),122(65,175),1,1) */
#ifdef XCASELABELS
  case 12:
#endif
    ALLOC_SIGNAL(confQ, ySigN_z05_confQ, TO_PROCESS(R, yPrsN_z01_R),
      XSIGNALHEADERTYPE)
    SIGNAL_ALLOC_ERROR
    SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, (xIdNode *)0, confQ,
      ySigN_z05_confQ, TO_PROCESS(R, yPrsN_z01_R), 0, "confQ")
    SIGNAL_ALLOC_ERROR_END
  } else {
    XBETWEEN_SYMBOLS(13, 1320)

/* ----- OUTPUT abortQ ----- */
/* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),119(105,175),1,1) */
#ifdef XCASELABELS
  case 13:
#endif
    ALLOC_SIGNAL(abortQ, ySigN_z06_abortQ, TO_PROCESS(R, yPrsN_z01_R),
      XSIGNALHEADERTYPE)
    SIGNAL_ALLOC_ERROR
    SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, (xIdNode *)0, abortQ,
      ySigN_z06_abortQ, TO_PROCESS(R, yPrsN_z01_R), 0, "abortQ")
    SIGNAL_ALLOC_ERROR_END
  }
    XBETWEEN_SYMBOLS(14, 1334)

/* ----- NEXTSTATE esp_Q ----- */
/* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),116(85,195),1,1) */
#ifdef XCASELABELS
  case 14:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(esp_Q, z024_esp_Q, "esp_Q")

/* ----- INPUT abortR in STATE esp_Q ----- */
/* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),194(110,120),1,1) */
  case 2:
    XDEBUG_LABEL(esp_Q_abortR)
    XAT_FIRST_SYMBOL(2)
    XOS_TRACE_INPUT("abortR")

/* ----- JOIN grst9271_1 ----- */
/* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),128(85,140),1,1) */
    goto L_grst9271_1;

/* ----- INPUT F in STATE esp_Q ----- */
/* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),212(145,120),1,1) */
  case 3:
    XDEBUG_LABEL(esp_Q_F)
    XAT_FIRST_SYMBOL(3)
    XOS_TRACE_INPUT("F")
    INPUT_TIMER_VAR(yVarP->yTim_F)

/* ----- JOIN 1 ----- */
/* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),215(150,140),1,1) */
    goto L_1;
  default : return;
  }
}

/*****
* STATE esp_Q
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS Q>>
* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),134(85,105),1,1)
******/
static XCONST xInputAction yStaH_z024_esp_Q[] = {xInput, xInput, xInput,
  xDiscard};
static XCONST XINPUTREFTYPE yStaI_z024_esp_Q[] = {1, 2, 3, 0};
#ifdef XCOVERAGE
static long int yStaC_z024_esp_Q[3+1];
#endif
XCONST struct xStateIdStruct yStaR_z024_esp_Q = {xStateEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_Q, "esp_Q" XCOMMON_EXTRAS, z024_esp_Q,
  yStaH_z024_esp_Q, yStaI_z024_esp_Q, 0, 0, 0 xCoverage(yStaC_z024_esp_Q),
  (xStateIdNode)0
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/Q.spr(1),134(85,105),1,1)") XSTA_EXTRAS};

/*****
* TIMER F
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS Q>>
* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),191(130,10),1,7)
******/
XCONST struct xSignalIdStruct ySigR_z025_F = {xTimerEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_Q, "F" XCOMMON_EXTRAS,
  (xptrint)sizeof(XTIMERHEADERTYPE), 0, 0 xFreS(0) SIGCODE(F)
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/Q.spr(1),191(130,10),1,7)")
  xSigPrioPar(xDefaultPrioSignal) OFFSET_TIMER_VAR(yTim_F, yVDef_z02_Q)
  XSIG_EXTRAS};

/*****
* DCL resQ
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque/PROCESS Q>>
* #SDTREF(SDL,/home/sdl/PQR/Q.spr(1),191(130,10),3,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z026_resQ = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_Q, "resQ" XCOMMON_EXTRAS, &xSrtR_SDL_Boolean,
  (tSDLTypeInfo *)&ySDL_SDL_Boolean, xOffsetOf(yVDef_z02_Q, z026_resQ),
  (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* SIGNAL confP
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),143(110,25),2,1)
******/
XCONST struct xSignalIdStruct ySigR_z03_confP = {xSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_PQR_bloque, "confP" XCOMMON_EXTRAS,
  (xptrint)sizeof(XSIGNALHEADERTYPE), 0, 0 xFreS(0) SIGCODE(confP)
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),143(110,25),2,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};

/*****
* SIGNAL abortP
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),143(110,25),3,1)
******/
XCONST struct xSignalIdStruct ySigR_z04_abortP = {xSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_PQR_bloque, "abortP" XCOMMON_EXTRAS,
  (xptrint)sizeof(XSIGNALHEADERTYPE), 0, 0 xFreS(0) SIGCODE(abortP)
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),143(110,25),3,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};

/*****
* SIGNAL confQ
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),143(110,25),4,1)
******/
XCONST struct xSignalIdStruct ySigR_z05_confQ = {xSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_PQR_bloque, "confQ" XCOMMON_EXTRAS,
  (xptrint)sizeof(XSIGNALHEADERTYPE), 0, 0 xFreS(0) SIGCODE(confQ)
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),143(110,25),4,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};

/*****
* SIGNAL abortQ
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),143(110,25),5,1)
******/
XCONST struct xSignalIdStruct ySigR_z06_abortQ = {xSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_PQR_bloque, "abortQ" XCOMMON_EXTRAS,
  (xptrint)sizeof(XSIGNALHEADERTYPE), 0, 0 xFreS(0) SIGCODE(abortQ)
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),143(110,25),5,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};

/*****
* SIGNAL confR
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),143(110,25),6,1)
******/
XCONST struct xSignalIdStruct ySigR_z07_confR = {xSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_PQR_bloque, "confR" XCOMMON_EXTRAS,
  (xptrint)sizeof(XSIGNALHEADERTYPE), 0, 0 xFreS(0) SIGCODE(confR)
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),143(110,25),6,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};

/*****
* SIGNAL abortR
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),143(110,25),7,1)
******/
XCONST struct xSignalIdStruct ySigR_z08_abortR = {xSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_PQR_bloque, "abortR" XCOMMON_EXTRAS,
  (xptrint)sizeof(XSIGNALHEADERTYPE), 0, 0 xFreS(0) SIGCODE(abortR)
  xBreakB("#SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),143(110,25),7,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};

/*****
* SIGNALROUTE R1
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),125(80,85),1,1)
******/
#ifndef XOPTCHAN
static XCONST XSIGTYPE yChaS_z09_R1[] = {SIGNAL_NAME(confP, &ySigR_z03_confP),
  SIGNAL_NAME(abortP, &ySigR_z04_abortP), (XSIGTYPE)0};
static XCONST XSIGTYPE yChaSR_z09_R1[] = {SIGNAL_NAME(confR, &ySigR_z07_confR),
  SIGNAL_NAME(abortR, &ySigR_z08_abortR), (XSIGTYPE)0};
XCONST xIdNode yChaO_z09_R1[] = {(xIdNode)&yPrsR_z01_R, (xIdNode)0};
XCONST xIdNode yChaOR_z09_R1[] = {(xIdNode)&yPrsR_z00_P, (xIdNode)0};
XCONST struct xChannelIdStruct yChaR_z09_R1 = {xSignalrouteEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_PQR_bloque, "R1" XCOMMON_EXTRAS, yChaS_z09_R1,
  yChaO_z09_R1, &yChaRR_z09_R1 XCHA_EXTRAS};
XCONST struct xChannelIdStruct yChaRR_z09_R1 = {xSignalrouteEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_PQR_bloque, "R1" XCOMMON_EXTRAS,
  yChaSR_z09_R1, yChaOR_z09_R1, &yChaR_z09_R1 XCHA_EXTRAS};
#endif

/*****
* SIGNALROUTE R2
* <<SYSTEM PQR_sistema/BLOCK PQR_bloque>>
* #SDTREF(SDL,/home/sdl/PQR/PQR_bloque.sbk(1),134(80,107),1,1)
******/
#ifndef XOPTCHAN
static XCONST XSIGTYPE yChaS_z0A_R2[] = {SIGNAL_NAME(confQ, &ySigR_z05_confQ),
  SIGNAL_NAME(abortQ, &ySigR_z06_abortQ), (XSIGTYPE)0};
static XCONST XSIGTYPE yChaSR_z0A_R2[] = {SIGNAL_NAME(confR, &ySigR_z07_confR),
  SIGNAL_NAME(abortR, &ySigR_z08_abortR), (XSIGTYPE)0};
XCONST xIdNode yChaO_z0A_R2[] = {(xIdNode)&yPrsR_z01_R, (xIdNode)0};
XCONST xIdNode yChaOR_z0A_R2[] = {(xIdNode)&yPrsR_z02_Q, (xIdNode)0};
XCONST struct xChannelIdStruct yChaR_z0A_R2 = {xSignalrouteEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_PQR_bloque, "R2" XCOMMON_EXTRAS, yChaS_z0A_R2,
  yChaO_z0A_R2, &yChaRR_z0A_R2 XCHA_EXTRAS};
XCONST struct xChannelIdStruct yChaRR_z0A_R2 = {xSignalrouteEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_PQR_bloque, "R2" XCOMMON_EXTRAS,
  yChaSR_z0A_R2, yChaOR_z0A_R2, &yChaR_z0A_R2 XCHA_EXTRAS};
#endif

/*************************************************************************
**                       SECTION Initialization                         **
*************************************************************************/
#ifndef XMULTIPLESYSTEMS
void yInit (void)
{
#else
void yInit_PQR_sistema (void)
{
#endif
  int  Temp;
  YINIT_TEMP_VARS
  BEGIN_YINIT

#ifdef XMONITOR
  xTranslatorVersion =
    "Program generated by Cbasic 6.3.0 13633";
#endif
  xInsertIdNode((xIdNode)&ySysR_z_PQR_sistema);
  xInsertIdNode((xIdNode)&yBloR_z0_PQR_bloque);
  xInsertIdNode((xIdNode)&yPrsR_z00_P);
  xInsertIdNode((xIdNode)&ySigR_z00_P);
  INIT_PROCESS_TYPE(P,z00_P,yPrsN_z00_P,"z00_P",-1,1,yVDef_z00_P,
    xDefaultPrioProcess,yPAD_z00_P)
#ifdef SDL_STATIC_CREATE
  SDL_STATIC_CREATE(P,z00_P,yPrsN_z00_P,"P",ySigN_z00_P,yPDef_z00_P,yVDef_z00_P,
    xDefaultPrioProcess,yPAD_z00_P,1)
#endif
  xInsertIdNode((xIdNode)&yStaR_z004_esp_P);
  xInsertIdNode((xIdNode)&ySigR_z005_T);
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z006_resP);
#endif
  xInsertIdNode((xIdNode)&yPrsR_z01_R);
  xInsertIdNode((xIdNode)&ySigR_z01_R);
  INIT_PROCESS_TYPE(R,z01_R,yPrsN_z01_R,"z01_R",-1,1,yVDef_z01_R,
    xDefaultPrioProcess,yPAD_z01_R)
#ifdef SDL_STATIC_CREATE
  SDL_STATIC_CREATE(R,z01_R,yPrsN_z01_R,"R",ySigN_z01_R,yPDef_z01_R,yVDef_z01_R,
    xDefaultPrioProcess,yPAD_z01_R,1)
#endif
  xInsertIdNode((xIdNode)&yStaR_z013_ListoR);
  xInsertIdNode((xIdNode)&yStaR_z014_espConfQ);
  xInsertIdNode((xIdNode)&yStaR_z015_espConP);
  xInsertIdNode((xIdNode)&yStaR_z016_espFallida);
  xInsertIdNode((xIdNode)&yPrsR_z02_Q);
  xInsertIdNode((xIdNode)&ySigR_z02_Q);
  INIT_PROCESS_TYPE(Q,z02_Q,yPrsN_z02_Q,"z02_Q",-1,1,yVDef_z02_Q,
    xDefaultPrioProcess,yPAD_z02_Q)
#ifdef SDL_STATIC_CREATE
  SDL_STATIC_CREATE(Q,z02_Q,yPrsN_z02_Q,"Q",ySigN_z02_Q,yPDef_z02_Q,yVDef_z02_Q,
    xDefaultPrioProcess,yPAD_z02_Q,1)
#endif
  xInsertIdNode((xIdNode)&yStaR_z024_esp_Q);
  xInsertIdNode((xIdNode)&ySigR_z025_F);
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z026_resQ);
#endif
  xInsertIdNode((xIdNode)&ySigR_z03_confP);
  xInsertIdNode((xIdNode)&ySigR_z04_abortP);
  xInsertIdNode((xIdNode)&ySigR_z05_confQ);
  xInsertIdNode((xIdNode)&ySigR_z06_abortQ);
  xInsertIdNode((xIdNode)&ySigR_z07_confR);
  xInsertIdNode((xIdNode)&ySigR_z08_abortR);
#ifndef XOPTCHAN
  xInsertIdNode((xIdNode)&yChaR_z09_R1);
  xInsertIdNode((xIdNode)&yChaRR_z09_R1);
#endif
#ifndef XOPTCHAN
  xInsertIdNode((xIdNode)&yChaR_z0A_R2);
  xInsertIdNode((xIdNode)&yChaRR_z0A_R2);
#endif
}
